# Generated by Django 4.2.2 on 2023-07-24 07:33

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                upload_to="videos/", validators=[video.models.validate_file_extension]
            ),
        ),
    ]
