# Generated by Django 3.2.4 on 2023-07-27 11:06

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=video.models.user_directory_path, validators=[video.models.validate_file_extension]),
        ),
    ]
