# Generated by Django 3.2.15 on 2023-08-01 22:02

from django.db import migrations, models
import video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processed_video_file',
            field=models.FileField(blank=True, null=True, upload_to=video.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=10),
        ),
    ]
