# Generated by Django 3.2.15 on 2023-08-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20230801_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='transcipt',
            new_name='transcript',
        ),
    ]
