# Generated by Django 4.2.2 on 2023-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_rename_transcipt_video_transcript"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="status",
            new_name="alphabets_status",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="transcript",
            new_name="transcript_alphabets",
        ),
        migrations.AddField(
            model_name="video",
            name="transcript_words",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="video",
            name="words_status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="UPLOADED",
                max_length=10,
            ),
        ),
    ]
